# Generated by Django 4.2.3 on 2023-07-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Category', models.CharField(choices=[['mb', 'Мебель'], ['dr', 'Одежда'], ['el', 'Электроника'], ['ot', 'Другое']], max_length=50)),
                ('Price', models.PositiveIntegerField()),
                ('Status', models.CharField(choices=[['false', 'Куплено'], ['true', 'Не куплено']], max_length=50)),
                ('Date', models.DateField()),
            ],
        ),
    ]
